#!/bin/bash
fixapt="apt clean & apt --fix-broken install -y & apt dist-upgrade --allow-downgrades -f "
fixdpkg="apt clean & dpkg --configure -a -y & apt install -f & apt dist-upgrade --allow-downgrades -f "
a='Please enter your choice: '
options=("apt issue fix" "dpkg issue fix" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "apt issue fix")
            echo " {sl0p} we gonna fix ur apt issues"
            sleep 3
            $fixapt
            ;;
        "dpkg issue fix")
            echo " {sl0p} we gonna fix ur dpkg issues"
            sleep 3
            $fixdpkg
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
