#!/bin/bash
#
# team sl0ppyr00t linux issue fixer 
# author : x0xr00t

fixapt="apt clean & apt --fix-broken install -y & apt full-upgrade --allow-downgrades -f "
fixdpkg="apt clean & dpkg --configure -a -y & apt install -f & --fix-broken install -y & apt full-upgrade --allow-downgrades -f"
fixchsum='echo "deb http://http.kali.org/kali kali-last-snapshot main contrib non-free" | sudo tee /etc/apt/sources.list'
apply="apt update -y"
upgrade="apt full-upgrade -f -y"
a='Please enter your choice: '
options=("APT Issue Fix" "CheckSum Error Fix" "DPKG Issue Fix" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "APT Issue Fix")
            echo " {sl0p} We Gonna Fix Ur APT Issues"
            sleep 3
            $fixapt
            ;;
        "CheckSUm Error fix")
            echo " {sl0p} We Gonna Fix Ur APT CheckSUm Issues"
            sleep 3
            $fixchsum
            sleep 2 
            echo " {sl0p} Applying Settings..." 
            $apply
            echo " {sl0p} We Gonna Upgrade Now. "
            $upgrade
            ;;            
        "DPKG Issue Fix")
            echo " {sl0p} We Gonna Fix Ur DPKG Issues"
            sleep 3
            $fixdpkg
            ;;
        "Quit")
            break
            ;;
        *) echo " {sl0p} invalid option $REPLY";;
    esac
done

