#!/bin/bash
#
# team sl0ppyr00t linux issue fixer 
# author : x0xr00t
if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi


fixapt="apt clean & apt --fix-missing -y"
fixdpkg="apt clean & dpkg --configure -a & apt install -f"
fixchsum='echo "deb http://http.kali.org/kali kali-last-snapshot main contrib non-free" | sudo tee /etc/apt/sources.list'
fixbroken="apt update --fix-broken install -y"
fixmissing="apt update --fix-missing -y"
apply="apt update -y"
upgrade="apt full-upgrade -y"
downgrade="apt clean & apt --fix-broken install -y & apt full-upgrade --allow-downgrades -y"
a='Please enter your choice: '
options=("APT Fix" "APT Broken Install Fix"  "APT Missing Fix" "CheckSum Fix" "DPKG Fix" "Apt Fix With Downgrade" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "APT Fix")
            echo " {sl0p} We Gonna Fix Ur APT Issues"
            sleep 3
            $fixapt
            sleep 2 
            echo " {sl0p} Applying Settings..." 
            $apply
            echo " {sl0p} We Gonna Upgrade Now. "
            $upgrade
            ;;
        "APT Broken Install Fix")
            echo " {sl0p} We Gonna Fix Ur Broken Install Issues"
            sleep 3
            $fixbroken
            sleep 2 
            echo " {sl0p} Applying Settings..." 
            $apply
            echo " {sl0p} We Gonna Upgrade Now. "
            $upgrade
            ;;
        "APT Missing Fix")
            echo " {sl0p} We Gonna Fix Ur Broken Install Issues"
            sleep 3
            $fixmissing
            sleep 2 
            echo " {sl0p} Applying Settings..." 
            $apply
            echo " {sl0p} We Gonna Upgrade Now. "
            $upgrade
            ;;            
        "CheckSum Fix")
            echo " {sl0p} We Gonna Fix Ur APT CheckSUm Issues"
            sleep 3
            $fixchsum
            sleep 2 
            echo " {sl0p} Applying Settings..." 
            $apply
            echo " {sl0p} We Gonna Upgrade Now. "
            $upgrade
            ;;            
        "DPKG Issue Fix")
            echo " {sl0p} We Gonna Fix Ur DPKG Issues"
            sleep 3
            $fixdpkg
            ;;
        "Apt Fix With Downgrade")
            echo " {sl0p} We Gonna Fix Ur APT Issues with downgrade."
            sleep 3
            $downgrade
            ;;            
        "Quit")
            break
            ;;
        *) echo " {sl0p} invalid option $REPLY";;
    esac
done

